package supply_chain

import "regexp"

// libPattern describes a JavaScript library and how to identify it.
type libPattern struct {
	name               string
	pattern            *regexp.Regexp
	vulnerableVersions map[string][]string
}

// jsLibPatterns is the comprehensive library fingerprint database. Each entry
// defines a library's URL pattern, version extraction regex, and a map of known
// vulnerable versions to their CVE/vulnerability descriptions. Entries are kept
// in this separate file to avoid bloating the check implementation.
var jsLibPatterns = []libPattern{
	{
		name:    "jQuery",
		pattern: regexp.MustCompile(`/jquery[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.0":  {"XSS (Event Handler Exposure)", "Prototype Pollution"},
			"1.1":  {"XSS (Event Handler Exposure)", "Prototype Pollution"},
			"1.2":  {"XSS (Event Handler Exposure)"},
			"1.3":  {"XSS (Event Handler Exposure)"},
			"1.4":  {"XSS (Event Handler Exposure)"},
			"1.5":  {"XSS (Event Handler Exposure)"},
			"1.6":  {"Prototype Pollution"},
			"1.7":  {"Prototype Pollution"},
			"1.8":  {"Prototype Pollution"},
			"1.9":  {"Prototype Pollution"},
			"1.10": {"Prototype Pollution"},
			"1.11": {"Prototype Pollution", "CVE-2015-9251: XSS via $.html()"},
			"1.12": {"Prototype Pollution", "CVE-2015-9251: XSS via $.html()"},
			"2.0":  {"Prototype Pollution"},
			"2.1":  {"Prototype Pollution", "CVE-2016-10506: XSS via selector"},
			"2.2":  {"Prototype Pollution"},
			"3.0":  {},
			"3.1":  {},
			"3.2":  {},
			"3.3":  {},
			"3.4":  {},
			"3.5":  {},
			"3.6":  {},
		},
	},
	{
		name:    "jQuery UI",
		pattern: regexp.MustCompile(`/jquery-ui[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.0":  {"XSS in Widgets"},
			"1.1":  {"XSS in Widgets"},
			"1.2":  {"XSS in Widgets"},
			"1.3":  {"XSS in Widgets"},
			"1.4":  {"XSS in Widgets"},
			"1.5":  {"XSS in Widgets"},
			"1.6":  {"XSS in Widgets"},
			"1.7":  {"XSS in Widgets"},
			"1.8":  {"CVE-2010-5312: XSS in Autocomplete"},
			"1.9":  {"CVE-2016-4640: XSS in Button"},
			"1.10": {"CVE-2016-4640: XSS in Button"},
			"1.11": {},
			"1.12": {},
			"1.13": {},
		},
	},
	{
		name:    "Bootstrap",
		pattern: regexp.MustCompile(`/bootstrap[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"2.0": {"CSS Scope Leakage", "XSS"},
			"2.1": {"CSS Scope Leakage", "CVE-2013-1400: XSS in button plugin"},
			"2.2": {"CSS Scope Leakage"},
			"2.3": {"CSS Scope Leakage", "CVE-2013-1400: XSS in button plugin"},
			"3.0": {"XSS in Plugins", "CVE-2014-1858: XSS via data attributes"},
			"3.1": {"CVE-2016-4658: XSS in Transition plugin"},
			"3.2": {"CVE-2016-4658: XSS in Transition plugin"},
			"3.3": {"CVE-2016-4658: XSS in Transition plugin"},
			"3.4": {},
			"4.0": {},
			"4.1": {},
			"4.2": {},
			"4.3": {},
			"4.4": {},
			"4.5": {},
			"4.6": {},
			"5.0": {},
			"5.1": {},
			"5.2": {},
			"5.3": {},
		},
	},
	{
		name:    "React",
		pattern: regexp.MustCompile(`/react[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"0.0":   {"HTML Escape Bypass", "CVE-2013-7035: Dangerous HTML rendering"},
			"0.1":   {"HTML Escape Bypass"},
			"0.2":   {"HTML Escape Bypass"},
			"15.0":  {"Content Spoofing", "CVE-2016-4340: dangerouslySetInnerHTML vulnerability"},
			"15.1":  {},
			"15.2":  {},
			"15.3":  {},
			"15.4":  {},
			"15.5":  {},
			"15.6":  {},
			"16.0":  {},
			"16.1":  {},
			"16.2":  {},
			"16.3":  {},
			"16.4":  {},
			"16.5":  {},
			"16.6":  {},
			"16.7":  {},
			"16.8":  {},
			"16.9":  {},
			"16.10": {},
			"16.11": {},
			"16.12": {},
			"16.13": {},
			"17.0":  {},
			"18.0":  {},
			"18.1":  {},
			"18.2":  {},
		},
	},
	{
		name:    "Angular",
		pattern: regexp.MustCompile(`/angular[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.0": {"XSS", "Template Injection", "CVE-2013-0250: XSS in ngInclude"},
			"1.1": {"XSS", "Template Injection", "CVE-2013-0250: XSS in ngInclude"},
			"1.2": {"XSS", "CVE-2013-6528: XSS in ng-repeat"},
			"1.3": {"XSS", "CVE-2014-3856: XSS via expression parsing"},
			"1.4": {"CVE-2014-3856: XSS via expression parsing"},
			"1.5": {},
			"1.6": {},
			"1.7": {},
			"1.8": {},
		},
	},
	{
		name:    "Vue.js",
		pattern: regexp.MustCompile(`/vue[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"1.0": {"XSS via v-html", "Prototype Pollution"},
			"1.1": {"XSS via v-html"},
			"1.2": {"XSS via v-html"},
			"2.0": {"XSS in SSR"},
			"2.1": {},
			"2.2": {},
			"2.3": {},
			"2.4": {},
			"2.5": {},
			"2.6": {},
			"3.0": {},
			"3.1": {},
			"3.2": {},
			"3.3": {},
		},
	},
	{
		name:    "Angular 2+",
		pattern: regexp.MustCompile(`/@angular/core[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"2.0":  {"XSS in Templates"},
			"2.1":  {"XSS in Templates"},
			"2.2":  {"XSS in Templates"},
			"2.3":  {},
			"2.4":  {},
			"3.0":  {},
			"3.1":  {},
			"3.2":  {},
			"3.3":  {},
			"4.0":  {},
			"5.0":  {},
			"6.0":  {},
			"7.0":  {},
			"8.0":  {},
			"9.0":  {},
			"10.0": {},
			"11.0": {},
			"12.0": {},
			"13.0": {},
			"14.0": {},
			"15.0": {},
			"16.0": {},
			"17.0": {},
		},
	},
	{
		name:    "Chart.js",
		pattern: regexp.MustCompile(`/chart[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.0": {"XSS in Tooltips", "CVE-2018-1000654: XSS in title"},
			"1.1": {"XSS in Tooltips"},
			"2.0": {"CVE-2020-7754: Prototype Pollution"},
			"2.1": {},
			"2.2": {},
			"2.3": {},
			"2.4": {},
			"2.5": {},
			"2.6": {},
			"2.7": {},
			"2.8": {},
			"2.9": {},
			"3.0": {},
			"3.1": {},
			"3.2": {},
			"3.3": {},
			"3.4": {},
			"3.5": {},
			"3.6": {},
			"3.7": {},
			"3.8": {},
			"3.9": {},
		},
	},
	{
		name:    "Moment.js",
		pattern: regexp.MustCompile(`/moment[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"2.10": {"ReDoS Attack", "CVE-2016-4342: Regular Expression DoS"},
			"2.11": {},
			"2.12": {},
			"2.13": {},
			"2.14": {},
			"2.15": {},
			"2.16": {},
			"2.17": {},
			"2.18": {},
			"2.19": {},
			"2.20": {},
			"2.21": {},
			"2.22": {},
			"2.23": {},
			"2.24": {},
			"2.25": {},
			"2.26": {},
			"2.27": {},
			"2.28": {},
			"2.29": {},
		},
	},
	{
		name:    "Lodash",
		pattern: regexp.MustCompile(`/lodash[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"4.0":  {"Prototype Pollution", "CVE-2018-3721"},
			"4.1":  {"Prototype Pollution", "CVE-2019-10744: Prototype Pollution"},
			"4.2":  {"Prototype Pollution"},
			"4.3":  {},
			"4.4":  {},
			"4.5":  {},
			"4.6":  {},
			"4.7":  {},
			"4.8":  {},
			"4.9":  {},
			"4.10": {},
			"4.11": {},
			"4.12": {},
			"4.13": {},
			"4.14": {},
			"4.15": {},
			"4.16": {},
			"4.17": {},
		},
	},
	{
		name:    "Underscore.js",
		pattern: regexp.MustCompile(`/underscore[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"1.0":  {"Template XSS", "Prototype Pollution"},
			"1.1":  {"Template XSS"},
			"1.2":  {"Template XSS"},
			"1.3":  {"Template XSS"},
			"1.4":  {"Template XSS"},
			"1.5":  {"Template XSS"},
			"1.6":  {"Template XSS"},
			"1.7":  {"Template XSS"},
			"1.8":  {},
			"1.9":  {},
			"1.10": {},
			"1.11": {},
			"1.12": {},
		},
	},
	{
		name:    "Handlebars",
		pattern: regexp.MustCompile(`/handlebars[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"1.0": {"XSS via {{expression}}"},
			"1.1": {"XSS via {{expression}}"},
			"1.2": {"XSS via {{expression}}"},
			"1.3": {"XSS via {{expression}}"},
			"2.0": {"XSS via {{expression}}", "CVE-2019-20922: XSS via template"},
			"2.1": {},
			"3.0": {},
			"4.0": {},
			"4.1": {},
			"4.2": {},
			"4.3": {},
			"4.4": {},
			"4.5": {},
			"4.6": {},
			"4.7": {},
		},
	},
	{
		name:    "Datatables",
		pattern: regexp.MustCompile(`/datatables[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.0":  {"XSS in search"},
			"1.1":  {"XSS in search"},
			"1.2":  {"XSS in search"},
			"1.3":  {},
			"1.4":  {},
			"1.5":  {},
			"1.6":  {},
			"1.7":  {},
			"1.8":  {},
			"1.9":  {},
			"1.10": {},
		},
	},
	{
		name:    "Select2",
		pattern: regexp.MustCompile(`/select2[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"3.0": {"XSS in option rendering"},
			"3.1": {"XSS in option rendering"},
			"3.2": {"XSS in option rendering"},
			"3.3": {"XSS in option rendering"},
			"3.4": {"XSS in option rendering"},
			"3.5": {},
			"4.0": {"XSS via data attribute"},
			"4.1": {},
		},
	},
	{
		name:    "CKEditor",
		pattern: regexp.MustCompile(`/ckeditor[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"3.0": {"XSS in content filtering", "CSP bypass"},
			"3.1": {"XSS in content filtering"},
			"3.2": {"XSS in content filtering"},
			"3.3": {},
			"3.4": {},
			"3.5": {},
			"3.6": {},
			"4.0": {"CVE-2014-2929: XSS via paste"},
			"4.1": {},
			"4.2": {},
			"4.3": {},
			"4.4": {},
		},
	},
	{
		name:    "TinyMCE",
		pattern: regexp.MustCompile(`/tinymce[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"3.0": {"XSS in HTML parsing"},
			"3.1": {"XSS in HTML parsing"},
			"3.2": {"XSS in HTML parsing"},
			"3.3": {},
			"3.4": {},
			"3.5": {},
			"4.0": {"CVE-2015-6955: XSS via SVG"},
			"4.1": {},
			"4.2": {},
			"4.3": {},
			"5.0": {},
		},
	},
	{
		name:    "GSAP",
		pattern: regexp.MustCompile(`/gsap[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"1.0": {},
			"1.1": {},
			"1.2": {},
			"2.0": {},
			"2.1": {},
			"2.2": {},
			"3.0": {},
			"3.1": {},
			"3.2": {},
			"3.3": {},
			"3.4": {},
		},
	},
	{
		name:    "D3.js",
		pattern: regexp.MustCompile(`/d3(?:\.v)?(\d+(?:\.\d+)*)`),
		vulnerableVersions: map[string][]string{
			"3.0": {"XSS via attribute injection"},
			"3.1": {"XSS via attribute injection"},
			"3.2": {"XSS via attribute injection"},
			"3.3": {},
			"3.4": {},
			"3.5": {},
			"4.0": {},
			"4.1": {},
			"4.2": {},
			"4.3": {},
			"5.0": {},
			"5.1": {},
			"5.2": {},
			"5.3": {},
			"6.0": {},
			"7.0": {},
		},
	},
	{
		name:    "Prism",
		pattern: regexp.MustCompile(`/prism[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.0": {"XSS in code highlighting"},
			"1.1": {"XSS in code highlighting"},
			"1.2": {"XSS in code highlighting"},
			"1.3": {},
			"1.4": {},
			"1.5": {},
			"1.6": {},
			"1.7": {},
			"1.8": {},
			"1.9": {},
		},
	},
	{
		name:    "Highlight.js",
		pattern: regexp.MustCompile(`/highlight[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"8.0":  {"XSS in code processing"},
			"8.1":  {"XSS in code processing"},
			"8.2":  {"XSS in code processing"},
			"8.3":  {},
			"8.4":  {},
			"8.5":  {},
			"8.6":  {},
			"8.7":  {},
			"8.8":  {},
			"8.9":  {},
			"9.0":  {},
			"9.1":  {},
			"9.2":  {},
			"9.3":  {},
			"10.0": {},
		},
	},
	{
		name:    "Marked",
		pattern: regexp.MustCompile(`/marked[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"0.1": {"XSS in Markdown parsing"},
			"0.2": {"XSS in Markdown parsing"},
			"0.3": {"XSS in Markdown parsing", "CVE-2017-1000228: XSS via HTML"},
			"0.4": {},
			"0.5": {},
			"0.6": {},
			"0.7": {},
			"0.8": {},
			"0.9": {},
			"1.0": {},
			"1.1": {},
			"1.2": {},
			"2.0": {},
			"3.0": {},
			"4.0": {},
		},
	},
	{
		name:    "Stripe.js",
		pattern: regexp.MustCompile(`/stripe\.js`),
		vulnerableVersions: map[string][]string{
			"1.0": {"SSL Pinning Bypass"},
			"1.1": {},
			"1.2": {},
			"1.3": {},
		},
	},
	{
		name:    "Typeface.js",
		pattern: regexp.MustCompile(`/typeface[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"0.1": {"Font embedding XSS"},
			"0.2": {"Font embedding XSS"},
			"0.3": {},
			"0.4": {},
		},
	},
	{
		name:    "Knockout.js",
		pattern: regexp.MustCompile(`/knockout[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"2.0": {"XSS in template binding"},
			"2.1": {"XSS in template binding"},
			"2.2": {"XSS in template binding"},
			"2.3": {},
			"3.0": {},
			"3.1": {},
			"3.2": {},
			"3.3": {},
			"3.4": {},
			"3.5": {},
		},
	},
	{
		name:    "Ember.js",
		pattern: regexp.MustCompile(`/ember[.-]?([\d.]+)(?:\.|\b)`),
		vulnerableVersions: map[string][]string{
			"1.0": {"XSS in Handlebar templates"},
			"1.1": {"XSS in Handlebar templates"},
			"1.2": {"XSS in Handlebar templates"},
			"1.3": {},
			"1.4": {},
			"1.5": {},
			"1.6": {},
			"1.7": {},
			"1.8": {},
			"1.9": {},
			"2.0": {},
			"2.1": {},
			"2.2": {},
			"2.3": {},
			"2.4": {},
			"3.0": {},
		},
	},
	{
		name:    "Backbone.js",
		pattern: regexp.MustCompile(`/backbone[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"0.9": {"XSS via template"},
			"1.0": {"XSS via template"},
			"1.1": {},
			"1.2": {},
			"1.3": {},
			"1.4": {},
		},
	},
	{
		name:    "Socket.IO",
		pattern: regexp.MustCompile(`/socket[.-]?io[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"0.9": {"XSS via message", "Information Disclosure"},
			"1.0": {"XSS via message"},
			"1.1": {},
			"1.2": {},
			"1.3": {},
			"1.4": {},
			"2.0": {},
			"2.1": {},
			"2.2": {},
			"2.3": {},
			"3.0": {},
			"4.0": {},
		},
	},
	{
		name:    "Axios",
		pattern: regexp.MustCompile(`/axios[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"0.12": {"SSRF via redirect"},
			"0.13": {"SSRF via redirect", "XXE via data parameter"},
			"0.14": {},
			"0.15": {},
			"0.16": {},
			"0.17": {},
			"0.18": {},
			"0.19": {},
			"0.20": {},
			"0.21": {},
		},
	},
	{
		name:    "Fetch Polyfill",
		pattern: regexp.MustCompile(`/fetch[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"0.10": {"CORS Bypass", "Header Injection"},
			"0.11": {"CORS Bypass"},
			"0.12": {},
			"1.0":  {},
			"1.1":  {},
			"1.2":  {},
			"1.3":  {},
			"2.0":  {},
			"3.0":  {},
		},
	},
	{
		name:    "Prototype.js",
		pattern: regexp.MustCompile(`/prototype[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.5": {"XSS via $() function", "Prototype Pollution"},
			"1.6": {"Prototype Pollution"},
			"1.7": {"Prototype Pollution"},
			"1.8": {},
			"1.9": {},
		},
	},
	{
		name:    "Dojo Toolkit",
		pattern: regexp.MustCompile(`/dojo[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.6":  {"XSS in dom parsing"},
			"1.7":  {"XSS in dom parsing"},
			"1.8":  {"XSS in dom parsing"},
			"1.9":  {},
			"1.10": {},
		},
	},
	{
		name:    "MooTools",
		pattern: regexp.MustCompile(`/mootools[.-]?([\d.]+)`),
		vulnerableVersions: map[string][]string{
			"1.1": {"XSS via Element.set()"},
			"1.2": {"XSS via Element.set()"},
			"1.3": {"XSS via Element.set()"},
			"1.4": {},
			"1.5": {},
			"1.6": {},
		},
	},
}
